export const t = {
  fr: {
    tabs: { all: 'Tous', articles: 'Articles', journals: 'Journaux', academies: 'Ecoles', institutions: 'Institutions', blogs: 'Blogs' },
    search: 'Rechercher une organisation...',
    submit: 'Soumettre une ressource',
    hero: { title: 'Explorez la recherche en santé en afrique', 
        subtitle: '  La plateforme de référence pour accéder aux journaux, académies et institutions de recherche en santé à travers l\'Afrique',
        about: 'À propos de cette ressource',
        website: 'Accès au site web',
        loadingdata:"Données encours de chargement...",
        statut:"Statut",
        explore:"Visiter",
        all:"Tous",
        resourcenotfound:"Ressource non trouvée",
        back:"Retour",
        close:"Fermer",
        name:"Nom/titre",
        description: "Description",
        selectedfile: "Fichier sélectionné: ",
        filedescription: "Sélectionnez une image (max 5MB) ou laissez vide pour l'image par défaut",
        uploading: "Upload en cours... ",
        cancel: "Annuler",
        sending: "Envoi...",
        submit: "Soumettre",
        uploadProgress: "Progression de l'upload: ",
        isbnnumber: "Numéro ISBN",
        statutdetails: "Description du statut",
        french: "Français",
        english:"Anglais",
        publishthe: "Publié le",
        language: "Langue",
        visionTitle: "Notre vision",
        visionTexts: [
          "Booster l'accès mondial aux recherches publiées dans les journaux africains. Des <strong class=\"text-amber-600\">millions</strong> d'articles de recherche africains sont téléchargés chaque mois, amplifiant la portée africaine et mondiale de la recherche du continent.",
          "Nous avons <strong class=\"text-amber-600\">répertorié des académies, des institutions et des organisations dans le domaine de la santé en Afrique</strong>, afin de faciliter l'accès aux savoirs, encourager les échanges scientifiques et valoriser les expertises locales sur la scène mondiale.",
          "<strong class=\"text-amber-600\">Afri-Fek</strong> soutient les <strong class=\"text-amber-600\"> modèles de publication Open Access et gratuits</strong>, et fournit l'accès à une gamme complète de ressources gratuites pour assister les chercheurs, auteurs, éditeurs et journaux africains."
        ] },
    filters: { type: 'Type de ressource', 
        country: 'Pays', clear: 'Effacer les filtres' , academy: 'Académie'},
    loading: 'Données encours de chargement...'
  },
  en: {
    tabs: { all: 'All', articles: 'Articles', journals: 'Journals', academies: 'Schools', institutions: 'Institutions', blogs: 'Blogs' },
    search: 'Search for an organization...',
    submit: 'Submit a resource',
    hero: { title: 'Explore the best African health resources',
         subtitle: 'Articles, journals, academies, institutions and blogs selected for you.',
        about: 'About this resource',
        website: 'Access the website',
        statut:"Status"  ,
        explore:"Explore" ,
        close:"Close" ,
        name:"Name/Title",
        description: "Description",
        selectedfile: "Selected file: ",
        filedescription: "Select an image (max 5MB) or leave empty for default image",
        uploading: "Uploading... ",
        cancel: "Cancel",
        sending: "Sending...",
        submit: "Submit",
        uploadProgress: "Upload progress: ",
        isbnnumber: "ISBN number",
        statutdetails: "Status description",
        french: "French",
        english:"English", 
        publishthe: "Published on", 
        language: "Language",
        visionTitle: "Our Vision",
        visionTexts: [
          "Boost global access to research published in African journals. <strong class=\"text-amber-600\">Millions</strong> of African research articles are downloaded monthly, amplifying the African and global reach of the continent's research.",
          "We have <strong class=\"text-amber-600\">listed academies, institutions and organizations in the field of health in Africa</strong>, in order to facilitate access to knowledge, encourage scientific exchanges and enhance local expertise on the global stage.",
          "<strong class=\"text-amber-600\">Afri-Fek</strong> supports <strong class=\"text-amber-600\">Open Access and free publication models</strong>, and provides access to a full range of free resources to assist African researchers, authors, editors and journals."
        ],
        all: "All",
        resourcenotfound: "Resource not found",
        back: "Back",
         },
    filters: { type: 'Resource type', country: 'Country', clear: 'Clear filters', academy: 'Academy' },
    loading: 'Data loading...'
  }
};
