export const getInitialResourceFormData = () => ({
  name: '',
  type: 'article',
  description: '',
  abbreviation: '',
  about: '',
  link: '',
  country: '',
  language: '',
  image: '',
  isbn: '',
  statut: '',
  detailsStatut: '',
  resourceLanguage: 'fr',
  organisationName: '',
  chiefEditor: '',
  email: '',
  articleType: 'pdf',
  frequency: 'monthly',
  licenseType: 'open-access',
  issnOnline: '',
  issnPrint: '',
  contactNumber: '',
  coverageStartYear: '',
  coverageEndYear: '',
  coverageStatus: 'ongoing',
  publisher: '',
  domainJournal: '',
  discipline: '',
});

export const mapFormDataToResourceForm = (formData: any) => ({
  resourceTitle: formData.name || '',
  resourceUrl: formData.link || '',
  abbreviation: formData.abbreviation || '',
  organisationName: formData.organisationName || '',
  chiefEditor: formData.chiefEditor || '',
  email: formData.email || '',
  articleType: formData.articleType || 'pdf',
  frequency: formData.frequency || 'monthly',
  licenseType: formData.licenseType || 'open-access',
  language: formData.resourceLanguage || 'fr',
  issnOnline: formData.issnOnline || '',
  issnPrint: formData.issnPrint || '',
  contactNumber: formData.contactNumber || '',
  country: formData.country || '',
  coverageStartYear: formData.coverageStartYear || '',
  coverageEndYear: formData.coverageEndYear || '',
  coverageStatus: formData.coverageStatus || 'ongoing',
  publisher: formData.publisher || '',
  domainJournal: formData.domainJournal || '',
  discipline: formData.discipline || '',
  type: formData.type || 'article',
  description: formData.description || '',
  about: formData.about || '',
  image: formData.image || ''
});

export const getFieldMapping = () => ({
  resourceTitle: 'name',
  resourceUrl: 'link',
  abbreviation: 'abbreviation',
  organisationName: 'organisationName',
  chiefEditor: 'chiefEditor',
  email: 'email',
  articleType: 'articleType',
  frequency: 'frequency',
  licenseType: 'licenseType',
  language: 'resourceLanguage',
  issnOnline: 'issnOnline',
  issnPrint: 'issnPrint',
  contactNumber: 'contactNumber',
  coverageStartYear: 'coverageStartYear',
  coverageEndYear: 'coverageEndYear',
  coverageStatus: 'coverageStatus',
  publisher: 'publisher',
  domainJournal: 'domainJournal',
  discipline: 'discipline'
});